server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: students
          url: //Url del microservicio
          predicate:
            - Path=/api/apiname/**
