spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888


  cloud:
    gateway:
          discovery:
            locator:
              enable: true
          routes:
            - id: all-routes
              uri: http://127.0.0.1:8000
              predicates:
                - Path=/**
eureka:
  client:
    register-with-eureka: false

server:
  port: 8080
